# See http://www.appveyor.com/docs/appveyor-yml for many more options

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /Update Readme and Manifest Version/

environment:
  access_token:
    secure: EJ2HHF0klBsYS3WlZWIvcc88u5/gixju8bcOR4d13x6Fh+BA7UNU89/NPkHYP6JN

# branches to build
branches:
  # whitelist
  only:
    - master

    
install:
  - choco install pester



